import { Question } from '@/types';

export const questions: Question[] = [
  {
    id: 'syn_01',
    type: 'syn',
    question: 'Choose the synonym for: CANDID',
    options: [
      { id: 'opt_syn_01_a', option: 'Secretive' },
      { id: 'opt_syn_01_b', option: 'Frank' },
      { id: 'opt_syn_01_c', option: 'Deceptive' },
      { id: 'opt_syn_01_d', option: 'Shy' },
    ],
    correctOptionId: 'opt_syn_01_b',
    answerExplanation: 'Candid means truthful and straightforward; frank.',
  },
  {
    id: 'syn_02',
    type: 'syn',
    question: 'Choose the synonym for: PRAGMATIC',
    options: [
      { id: 'opt_syn_02_a', option: 'Practical' },
      { id: 'opt_syn_02_b', option: 'Idealistic' },
      { id: 'opt_syn_02_c', option: 'Dreamy' },
      { id: 'opt_syn_02_d', option: 'Theoretical' },
    ],
    correctOptionId: 'opt_syn_02_a',
    answerExplanation: 'Pragmatic means dealing with things sensibly and realistically; practical.',
  },
  {
    id: 'syn_03',
    type: 'syn',
    question: 'Choose the synonym for: DILIGENT',
    options: [
      { id: 'opt_syn_03_a', option: 'Lazy' },
      { id: 'opt_syn_03_b', option: 'Hardworking' },
      { id: 'opt_syn_03_c', option: 'Careless' },
      { id: 'opt_syn_03_d', option: 'Confused' },
    ],
    correctOptionId: 'opt_syn_03_b',
    answerExplanation:
      "Diligent means having or showing care and conscientiousness in one's work; hardworking.",
  },
  {
    id: 'syn_04',
    type: 'syn',
    question: 'Choose the synonym for: LUCID',
    options: [
      { id: 'opt_syn_04_a', option: 'Clear' },
      { id: 'opt_syn_04_b', option: 'Murky' },
      { id: 'opt_syn_04_c', option: 'Confusing' },
      { id: 'opt_syn_04_d', option: 'Dark' },
    ],
    correctOptionId: 'opt_syn_04_a',
    answerExplanation: 'Lucid means expressed clearly; easy to understand.',
  },
  {
    id: 'syn_05',
    type: 'syn',
    question: 'Choose the synonym for: TENACIOUS',
    options: [
      { id: 'opt_syn_05_a', option: 'Weak' },
      { id: 'opt_syn_05_b', option: 'Persistent' },
      { id: 'opt_syn_05_c', option: 'Afraid' },
      { id: 'opt_syn_05_d', option: 'Yielding' },
    ],
    correctOptionId: 'opt_syn_05_b',
    answerExplanation:
      'Tenacious means tending to keep a firm hold of something; clinging or closely adhering. Synonymous with persistent.',
  },
  {
    id: 'syn_06',
    type: 'syn',
    question: 'Choose the synonym for: AESTHETIC',
    options: [
      { id: 'opt_syn_06_a', option: 'Ugly' },
      { id: 'opt_syn_06_b', option: 'Artistic' },
      { id: 'opt_syn_06_c', option: 'Rough' },
      { id: 'opt_syn_06_d', option: 'Plain' },
    ],
    correctOptionId: 'opt_syn_06_b',
    answerExplanation: 'Aesthetic relates to the appreciation of beauty or art.',
  },
  {
    id: 'syn_07',
    type: 'syn',
    question: 'Choose the synonym for: MUNDANE',
    options: [
      { id: 'opt_syn_07_a', option: 'Exciting' },
      { id: 'opt_syn_07_b', option: 'Ordinary' },
      { id: 'opt_syn_07_c', option: 'Extraordinary' },
      { id: 'opt_syn_07_d', option: 'Heavenly' },
    ],
    correctOptionId: 'opt_syn_07_b',
    answerExplanation: 'Mundane means lacking interest or excitement; dull or ordinary.',
  },
  {
    id: 'syn_08',
    type: 'syn',
    question: 'Choose the synonym for: PROLIFIC',
    options: [
      { id: 'opt_syn_08_a', option: 'Barren' },
      { id: 'opt_syn_08_b', option: 'Productive' },
      { id: 'opt_syn_08_c', option: 'Scarce' },
      { id: 'opt_syn_08_d', option: 'Lazy' },
    ],
    correctOptionId: 'opt_syn_08_b',
    answerExplanation:
      'Prolific means producing much fruit, foliage, or offspring; highly productive.',
  },
  {
    id: 'syn_09',
    type: 'syn',
    question: 'Choose the synonym for: VENERATE',
    options: [
      { id: 'opt_syn_09_a', option: 'Despise' },
      { id: 'opt_syn_09_b', option: 'Respect' },
      { id: 'opt_syn_09_c', option: 'Ignore' },
      { id: 'opt_syn_09_d', option: 'Mock' },
    ],
    correctOptionId: 'opt_syn_09_b',
    answerExplanation: 'Venerate means to regard with great respect; revere.',
  },
  {
    id: 'syn_10',
    type: 'syn',
    question: 'Choose the synonym for: EPHEMERAL',
    options: [
      { id: 'opt_syn_10_a', option: 'Permanent' },
      { id: 'opt_syn_10_b', option: 'Long-lasting' },
      { id: 'opt_syn_10_c', option: 'Short-lived' },
      { id: 'opt_syn_10_d', option: 'Eternal' },
    ],
    correctOptionId: 'opt_syn_10_c',
    answerExplanation: 'Ephemeral means lasting for a very short time.',
  },
  {
    id: 'syn_11',
    type: 'syn',
    question: 'Choose the synonym for: SUPERFLUOUS',
    options: [
      { id: 'opt_syn_11_a', option: 'Necessary' },
      { id: 'opt_syn_11_b', option: 'Unnecessary' },
      { id: 'opt_syn_11_c', option: 'Essential' },
      { id: 'opt_syn_11_d', option: 'Wanted' },
    ],
    correctOptionId: 'opt_syn_11_b',
    answerExplanation: 'Superfluous means unnecessary, especially through being more than enough.',
  },
  {
    id: 'syn_12',
    type: 'syn',
    question: 'Choose the synonym for: AMICABLE',
    options: [
      { id: 'opt_syn_12_a', option: 'Hostile' },
      { id: 'opt_syn_12_b', option: 'Friendly' },
      { id: 'opt_syn_12_c', option: 'Angry' },
      { id: 'opt_syn_12_d', option: 'Sad' },
    ],
    correctOptionId: 'opt_syn_12_b',
    answerExplanation:
      'Amicable means having a spirit of friendliness; without serious disagreement.',
  },
  {
    id: 'syn_13',
    type: 'syn',
    question: 'Choose the synonym for: NONCHALANT',
    options: [
      { id: 'opt_syn_13_a', option: 'Anxious' },
      { id: 'opt_syn_13_b', option: 'Unconcerned' },
      { id: 'opt_syn_13_c', option: 'Interested' },
      { id: 'opt_syn_13_d', option: 'Excited' },
    ],
    correctOptionId: 'opt_syn_13_b',
    answerExplanation:
      'Nonchalant means appearing casually calm and relaxed; not displaying anxiety, interest, or enthusiasm.',
  },
  {
    id: 'syn_14',
    type: 'syn',
    question: 'Choose the synonym for: INTREPID',
    options: [
      { id: 'opt_syn_14_a', option: 'Fearless' },
      { id: 'opt_syn_14_b', option: 'Cowardly' },
      { id: 'opt_syn_14_c', option: 'Weak' },
      { id: 'opt_syn_14_d', option: 'Slow' },
    ],
    correctOptionId: 'opt_syn_14_a',
    answerExplanation: 'Intrepid means fearless; adventurous.',
  },
  {
    id: 'syn_15',
    type: 'syn',
    question: 'Choose the synonym for: SAGACIOUS',
    options: [
      { id: 'opt_syn_15_a', option: 'Foolish' },
      { id: 'opt_syn_15_b', option: 'Wise' },
      { id: 'opt_syn_15_c', option: 'Young' },
      { id: 'opt_syn_15_d', option: 'Reckless' },
    ],
    correctOptionId: 'opt_syn_15_b',
    answerExplanation:
      'Sagacious means having or showing keen mental discernment and good judgment; wise.',
  },
  {
    id: 'syn_16',
    type: 'syn',
    question: 'Choose the synonym for: RECLUSIVE',
    options: [
      { id: 'opt_syn_16_a', option: 'Social' },
      { id: 'opt_syn_16_b', option: 'Isolated' },
      { id: 'opt_syn_16_c', option: 'Popular' },
      { id: 'opt_syn_16_d', option: 'Public' },
    ],
    correctOptionId: 'opt_syn_16_b',
    answerExplanation: 'Reclusive means avoiding the company of other people; solitary.',
  },
  {
    id: 'syn_17',
    type: 'syn',
    question: 'Choose the synonym for: ALLEVIATE',
    options: [
      { id: 'opt_syn_17_a', option: 'Worsen' },
      { id: 'opt_syn_17_b', option: 'Relieve' },
      { id: 'opt_syn_17_c', option: 'Increase' },
      { id: 'opt_syn_17_d', option: 'Stop' },
    ],
    correctOptionId: 'opt_syn_17_b',
    answerExplanation: 'Alleviate means to make suffering, deficiency, or a problem less severe.',
  },
  {
    id: 'syn_18',
    type: 'syn',
    question: 'Choose the synonym for: ELUSIVE',
    options: [
      { id: 'opt_syn_18_a', option: 'Obvious' },
      { id: 'opt_syn_18_b', option: 'Slippery' },
      { id: 'opt_syn_18_c', option: 'Direct' },
      { id: 'opt_syn_18_d', option: 'Stable' },
    ],
    correctOptionId: 'opt_syn_18_b',
    answerExplanation: 'Elusive means difficult to find, catch, or achieve.',
  },
  {
    id: 'syn_19',
    type: 'syn',
    question: 'Choose the synonym for: METICULOUS',
    options: [
      { id: 'opt_syn_19_a', option: 'Careful' },
      { id: 'opt_syn_19_b', option: 'Messy' },
      { id: 'opt_syn_19_c', option: 'Fast' },
      { id: 'opt_syn_19_d', option: 'Careless' },
    ],
    correctOptionId: 'opt_syn_19_a',
    answerExplanation:
      'Meticulous means showing great attention to detail; very careful and precise.',
  },
  {
    id: 'syn_20',
    type: 'syn',
    question: 'Choose the synonym for: ADVERSITY',
    options: [
      { id: 'opt_syn_20_a', option: 'Luck' },
      { id: 'opt_syn_20_b', option: 'Hardship' },
      { id: 'opt_syn_20_c', option: 'Peace' },
      { id: 'opt_syn_20_d', option: 'Benefit' },
    ],
    correctOptionId: 'opt_syn_20_b',
    answerExplanation: 'Adversity refers to a difficult or unpleasant situation; misfortune.',
  },
  {
    id: 'ant_01',
    type: 'ant',
    question: 'Choose the antonym for: ARROGANT',
    options: [
      { id: 'opt_ant_01_a', option: 'Humble' },
      { id: 'opt_ant_01_b', option: 'Proud' },
      { id: 'opt_ant_01_c', option: 'Vain' },
      { id: 'opt_ant_01_d', option: 'Confident' },
    ],
    correctOptionId: 'opt_ant_01_a',
    answerExplanation:
      "Arrogant means having an exaggerated sense of one's own importance. Humble is the opposite.",
  },
  {
    id: 'ant_02',
    type: 'ant',
    question: 'Choose the antonym for: OPTIMISTIC',
    options: [
      { id: 'opt_ant_02_a', option: 'Hopeful' },
      { id: 'opt_ant_02_b', option: 'Pessimistic' },
      { id: 'opt_ant_02_c', option: 'Cheerful' },
      { id: 'opt_ant_02_d', option: 'Realistic' },
    ],
    correctOptionId: 'opt_ant_02_b',
    answerExplanation:
      'Optimistic means expecting good things to happen. Pessimistic means expecting the worst.',
  },
  {
    id: 'ant_03',
    type: 'ant',
    question: 'Choose the antonym for: BENEVOLENT',
    options: [
      { id: 'opt_ant_03_a', option: 'Kind' },
      { id: 'opt_ant_03_b', option: 'Malevolent' },
      { id: 'opt_ant_03_c', option: 'Generous' },
      { id: 'opt_ant_03_d', option: 'Friendly' },
    ],
    correctOptionId: 'opt_ant_03_b',
    answerExplanation:
      'Benevolent means well-meaning and kindly. Malevolent means having a wish to do evil to others.',
  },
  {
    id: 'ant_04',
    type: 'ant',
    question: 'Choose the antonym for: CHAOS',
    options: [
      { id: 'opt_ant_04_a', option: 'Disorder' },
      { id: 'opt_ant_04_b', option: 'Order' },
      { id: 'opt_ant_04_c', option: 'Confusion' },
      { id: 'opt_ant_04_d', option: 'Mess' },
    ],
    correctOptionId: 'opt_ant_04_b',
    answerExplanation:
      'Chaos implies complete disorder. Order is the state of being arranged neatly.',
  },
  {
    id: 'ant_05',
    type: 'ant',
    question: 'Choose the antonym for: ARTIFICIAL',
    options: [
      { id: 'opt_ant_05_a', option: 'Synthetic' },
      { id: 'opt_ant_05_b', option: 'Natural' },
      { id: 'opt_ant_05_c', option: 'False' },
      { id: 'opt_ant_05_d', option: 'Man-made' },
    ],
    correctOptionId: 'opt_ant_05_b',
    answerExplanation:
      'Artificial means made by human beings rather than occurring naturally. Natural is the direct opposite.',
  },
  {
    id: 'ant_06',
    type: 'ant',
    question: 'Choose the antonym for: EXPAND',
    options: [
      { id: 'opt_ant_06_a', option: 'Increase' },
      { id: 'opt_ant_06_b', option: 'Contract' },
      { id: 'opt_ant_06_c', option: 'Grow' },
      { id: 'opt_ant_06_d', option: 'Extend' },
    ],
    correctOptionId: 'opt_ant_06_b',
    answerExplanation:
      'Expand means to become larger. Contract means to decrease in size, number, or range.',
  },
  {
    id: 'ant_07',
    type: 'ant',
    question: 'Choose the antonym for: PERMANENT',
    options: [
      { id: 'opt_ant_07_a', option: 'Temporary' },
      { id: 'opt_ant_07_b', option: 'Lasting' },
      { id: 'opt_ant_07_c', option: 'Eternal' },
      { id: 'opt_ant_07_d', option: 'Stable' },
    ],
    correctOptionId: 'opt_ant_07_a',
    answerExplanation:
      'Permanent means lasting indefinitely. Temporary means lasting for only a limited period.',
  },
  {
    id: 'ant_08',
    type: 'ant',
    question: 'Choose the antonym for: PLENTIFUL',
    options: [
      { id: 'opt_ant_08_a', option: 'Abundant' },
      { id: 'opt_ant_08_b', option: 'Scarce' },
      { id: 'opt_ant_08_c', option: 'Many' },
      { id: 'opt_ant_08_d', option: 'Full' },
    ],
    correctOptionId: 'opt_ant_08_b',
    answerExplanation:
      'Plentiful means existing in great quantities. Scarce means insufficient for the demand.',
  },
  {
    id: 'ant_09',
    type: 'ant',
    question: 'Choose the antonym for: TRANSPARENT',
    options: [
      { id: 'opt_ant_09_a', option: 'Clear' },
      { id: 'opt_ant_09_b', option: 'Opaque' },
      { id: 'opt_ant_09_c', option: 'See-through' },
      { id: 'opt_ant_09_d', option: 'Glassy' },
    ],
    correctOptionId: 'opt_ant_09_b',
    answerExplanation:
      'Transparent allows light to pass through. Opaque is not able to be seen through; not transparent.',
  },
  {
    id: 'ant_10',
    type: 'ant',
    question: 'Choose the antonym for: VOLUNTARY',
    options: [
      { id: 'opt_ant_10_a', option: 'Optional' },
      { id: 'opt_ant_10_b', option: 'Mandatory' },
      { id: 'opt_ant_10_c', option: 'Free' },
      { id: 'opt_ant_10_d', option: 'Willing' },
    ],
    correctOptionId: 'opt_ant_10_b',
    answerExplanation:
      "Voluntary means done of one's own free will. Mandatory means required by law or rules; compulsory.",
  },
  {
    id: 'ant_11',
    type: 'ant',
    question: 'Choose the antonym for: ANCIENT',
    options: [
      { id: 'opt_ant_11_a', option: 'Old' },
      { id: 'opt_ant_11_b', option: 'Modern' },
      { id: 'opt_ant_11_c', option: 'Antique' },
      { id: 'opt_ant_11_d', option: 'Past' },
    ],
    correctOptionId: 'opt_ant_11_b',
    answerExplanation:
      'Ancient refers to the very distant past. Modern relates to the present or recent times.',
  },
  {
    id: 'ant_12',
    type: 'ant',
    question: 'Choose the antonym for: COMPLEX',
    options: [
      { id: 'opt_ant_12_a', option: 'Complicated' },
      { id: 'opt_ant_12_b', option: 'Simple' },
      { id: 'opt_ant_12_c', option: 'Mixed' },
      { id: 'opt_ant_12_d', option: 'Hard' },
    ],
    correctOptionId: 'opt_ant_12_b',
    answerExplanation:
      'Complex means consisting of many different and connected parts. Simple means easily understood or done.',
  },
  {
    id: 'ant_13',
    type: 'ant',
    question: 'Choose the antonym for: STRENGTHEN',
    options: [
      { id: 'opt_ant_13_a', option: 'Weaken' },
      { id: 'opt_ant_13_b', option: 'Fortify' },
      { id: 'opt_ant_13_c', option: 'Build' },
      { id: 'opt_ant_13_d', option: 'Support' },
    ],
    correctOptionId: 'opt_ant_13_a',
    answerExplanation: 'Strengthen means to make stronger. Weaken means to make or become weaker.',
  },
  {
    id: 'ant_14',
    type: 'ant',
    question: 'Choose the antonym for: GUILTY',
    options: [
      { id: 'opt_ant_14_a', option: 'Innocent' },
      { id: 'opt_ant_14_b', option: 'Ashamed' },
      { id: 'opt_ant_14_c', option: 'Sorry' },
      { id: 'opt_ant_14_d', option: 'Responsible' },
    ],
    correctOptionId: 'opt_ant_14_a',
    answerExplanation:
      'Guilty means responsible for a wrongdoing. Innocent means not guilty of a crime or offense.',
  },
  {
    id: 'ant_15',
    type: 'ant',
    question: 'Choose the antonym for: ZENITH',
    options: [
      { id: 'opt_ant_15_a', option: 'Peak' },
      { id: 'opt_ant_15_b', option: 'Nadir' },
      { id: 'opt_ant_15_c', option: 'Top' },
      { id: 'opt_ant_15_d', option: 'Summit' },
    ],
    correctOptionId: 'opt_ant_15_b',
    answerExplanation: 'Zenith is the highest point. Nadir is the lowest point.',
  },
  {
    id: 'ant_16',
    type: 'ant',
    question: 'Choose the antonym for: BRAVERY',
    options: [
      { id: 'opt_ant_16_a', option: 'Courage' },
      { id: 'opt_ant_16_b', option: 'Cowardice' },
      { id: 'opt_ant_16_c', option: 'Heroism' },
      { id: 'opt_ant_16_d', option: 'Valor' },
    ],
    correctOptionId: 'opt_ant_16_b',
    answerExplanation: 'Bravery is courageous behavior. Cowardice is lack of bravery.',
  },
  {
    id: 'ant_17',
    type: 'ant',
    question: 'Choose the antonym for: IGNITE',
    options: [
      { id: 'opt_ant_17_a', option: 'Light' },
      { id: 'opt_ant_17_b', option: 'Extinguish' },
      { id: 'opt_ant_17_c', option: 'Burn' },
      { id: 'opt_ant_17_d', option: 'Start' },
    ],
    correctOptionId: 'opt_ant_17_b',
    answerExplanation:
      'Ignite means to catch fire or cause to catch fire. Extinguish means to put out a fire.',
  },
  {
    id: 'ant_18',
    type: 'ant',
    question: 'Choose the antonym for: PROFESSIONAL',
    options: [
      { id: 'opt_ant_18_a', option: 'Expert' },
      { id: 'opt_ant_18_b', option: 'Amateur' },
      { id: 'opt_ant_18_c', option: 'Paid' },
      { id: 'opt_ant_18_d', option: 'Skilled' },
    ],
    correctOptionId: 'opt_ant_18_b',
    answerExplanation:
      'A professional gets paid for a skill. An amateur engages in a pursuit on an unpaid basis.',
  },
  {
    id: 'ant_19',
    type: 'ant',
    question: 'Choose the antonym for: RIGID',
    options: [
      { id: 'opt_ant_19_a', option: 'Stiff' },
      { id: 'opt_ant_19_b', option: 'Flexible' },
      { id: 'opt_ant_19_c', option: 'Hard' },
      { id: 'opt_ant_19_d', option: 'Solid' },
    ],
    correctOptionId: 'opt_ant_19_b',
    answerExplanation:
      'Rigid means unable to bend. Flexible means capable of bending easily without breaking.',
  },
  {
    id: 'ant_20',
    type: 'ant',
    question: 'Choose the antonym for: VICTORY',
    options: [
      { id: 'opt_ant_20_a', option: 'Win' },
      { id: 'opt_ant_20_b', option: 'Defeat' },
      { id: 'opt_ant_20_c', option: 'Triumph' },
      { id: 'opt_ant_20_d', option: 'Success' },
    ],
    correctOptionId: 'opt_ant_20_b',
    answerExplanation:
      'Victory is an act of defeating an enemy. Defeat is the state of having been beaten.',
  },
  {
    id: 'idi_01',
    type: 'idi',
    question: "What is the meaning of: 'Bite the bullet'?",
    options: [
      { id: 'opt_idi_01_a', option: 'To eat quickly' },
      { id: 'opt_idi_01_b', option: 'To endure a painful situation with courage' },
      { id: 'opt_idi_01_c', option: 'To start a fight' },
      { id: 'opt_idi_01_d', option: 'To give up' },
    ],
    correctOptionId: 'opt_idi_01_b',
    answerExplanation: 'To force yourself to do something unpleasant or difficult.',
  },
  {
    id: 'idi_02',
    type: 'idi',
    question: "What is the meaning of: 'Break the ice'?",
    options: [
      { id: 'opt_idi_02_a', option: 'To shatter something frozen' },
      { id: 'opt_idi_02_b', option: 'To make people feel more comfortable in a social situation' },
      { id: 'opt_idi_02_c', option: 'To start a conflict' },
      { id: 'opt_idi_02_d', option: 'To end a relationship' },
    ],
    correctOptionId: 'opt_idi_02_b',
    answerExplanation: 'To do or say something to relieve tension or get conversation going.',
  },
  {
    id: 'idi_03',
    type: 'idi',
    question: "What is the meaning of: 'Cost an arm and a leg'?",
    options: [
      { id: 'opt_idi_03_a', option: 'To be physically painful' },
      { id: 'opt_idi_03_b', option: 'To be very expensive' },
      { id: 'opt_idi_03_c', option: 'To require surgery' },
      { id: 'opt_idi_03_d', option: 'To be very cheap' },
    ],
    correctOptionId: 'opt_idi_03_b',
    answerExplanation: 'An idiom meaning that something is extremely expensive.',
  },
  {
    id: 'idi_04',
    type: 'idi',
    question: "What is the meaning of: 'Hit the sack'?",
    options: [
      { id: 'opt_idi_04_a', option: 'To go to sleep' },
      { id: 'opt_idi_04_b', option: 'To punch a bag' },
      { id: 'opt_idi_04_c', option: 'To get fired' },
      { id: 'opt_idi_04_d', option: 'To win a game' },
    ],
    correctOptionId: 'opt_idi_04_a',
    answerExplanation: "An informal way of saying 'go to bed' or 'go to sleep'.",
  },
  {
    id: 'idi_05',
    type: 'idi',
    question: "What is the meaning of: 'Under the weather'?",
    options: [
      { id: 'opt_idi_05_a', option: 'Standing in the rain' },
      { id: 'opt_idi_05_b', option: 'Feeling sick or unwell' },
      { id: 'opt_idi_05_c', option: 'Being depressed' },
      { id: 'opt_idi_05_d', option: 'Being broke' },
    ],
    correctOptionId: 'opt_idi_05_b',
    answerExplanation: 'To feel slightly ill or not your usual self.',
  },
  {
    id: 'idi_06',
    type: 'idi',
    question: "What is the meaning of: 'Spill the beans'?",
    options: [
      { id: 'opt_idi_06_a', option: 'To make a mess' },
      { id: 'opt_idi_06_b', option: 'To reveal a secret' },
      { id: 'opt_idi_06_c', option: 'To cook dinner' },
      { id: 'opt_idi_06_d', option: 'To plant a garden' },
    ],
    correctOptionId: 'opt_idi_06_b',
    answerExplanation: 'To disclose a secret or reveal information prematurely.',
  },
  {
    id: 'idi_07',
    type: 'idi',
    question: "What is the meaning of: 'Piece of cake'?",
    options: [
      { id: 'opt_idi_07_a', option: 'Something very easy to do' },
      { id: 'opt_idi_07_b', option: 'A delicious dessert' },
      { id: 'opt_idi_07_c', option: 'A share of profits' },
      { id: 'opt_idi_07_d', option: 'Something hard to achieve' },
    ],
    correctOptionId: 'opt_idi_07_a',
    answerExplanation: 'Something that is easily achieved.',
  },
  {
    id: 'idi_08',
    type: 'idi',
    question: "What is the meaning of: 'Once in a blue moon'?",
    options: [
      { id: 'opt_idi_08_a', option: 'Every month' },
      { id: 'opt_idi_08_b', option: 'Very rarely' },
      { id: 'opt_idi_08_c', option: 'When you are sad' },
      { id: 'opt_idi_08_d', option: 'At night' },
    ],
    correctOptionId: 'opt_idi_08_b',
    answerExplanation: 'Refers to an event that happens very infrequently.',
  },
  {
    id: 'idi_09',
    type: 'idi',
    question: "What is the meaning of: 'Burn the midnight oil'?",
    options: [
      { id: 'opt_idi_09_a', option: 'To waste fuel' },
      { id: 'opt_idi_09_b', option: 'To work late into the night' },
      { id: 'opt_idi_09_c', option: 'To start a fire' },
      { id: 'opt_idi_09_d', option: 'To cook late' },
    ],
    correctOptionId: 'opt_idi_09_b',
    answerExplanation: 'To read or work late into the night.',
  },
  {
    id: 'idi_10',
    type: 'idi',
    question: "What is the meaning of: 'Cry over spilt milk'?",
    options: [
      { id: 'opt_idi_10_a', option: 'To be upset about a mistake that cannot be undone' },
      { id: 'opt_idi_10_b', option: 'To clean up a mess' },
      { id: 'opt_idi_10_c', option: 'To cry because you are hungry' },
      { id: 'opt_idi_10_d', option: 'To be wasteful' },
    ],
    correctOptionId: 'opt_idi_10_a',
    answerExplanation:
      'There is no point in being upset over something that has already happened and cannot be changed.',
  },
  {
    id: 'idi_11',
    type: 'idi',
    question: "What is the meaning of: 'Cut corners'?",
    options: [
      { id: 'opt_idi_11_a', option: 'To do something thoroughly' },
      { id: 'opt_idi_11_b', option: 'To do something poorly to save time or money' },
      { id: 'opt_idi_11_c', option: 'To drive fast' },
      { id: 'opt_idi_11_d', option: 'To use scissors' },
    ],
    correctOptionId: 'opt_idi_11_b',
    answerExplanation:
      'To do something in the easiest, cheapest, or fastest way, often at the expense of quality.',
  },
  {
    id: 'idi_12',
    type: 'idi',
    question: "What is the meaning of: 'Devil's advocate'?",
    options: [
      { id: 'opt_idi_12_a', option: 'Someone who supports the devil' },
      { id: 'opt_idi_12_b', option: 'Someone who argues against a popular view to provoke debate' },
      { id: 'opt_idi_12_c', option: 'A lawyer' },
      { id: 'opt_idi_12_d', option: 'A bad person' },
    ],
    correctOptionId: 'opt_idi_12_b',
    answerExplanation:
      'A person who expresses a contentious opinion in order to provoke debate or test the strength of the opposing arguments.',
  },
  {
    id: 'idi_13',
    type: 'idi',
    question: "What is the meaning of: 'Miss the boat'?",
    options: [
      { id: 'opt_idi_13_a', option: 'To be late for a trip' },
      { id: 'opt_idi_13_b', option: 'To miss an opportunity' },
      { id: 'opt_idi_13_c', option: 'To fail a test' },
      { id: 'opt_idi_13_d', option: 'To fall into water' },
    ],
    correctOptionId: 'opt_idi_13_b',
    answerExplanation: 'To be too slow to take advantage of an opportunity.',
  },
  {
    id: 'idi_14',
    type: 'idi',
    question: "What is the meaning of: 'On the ball'?",
    options: [
      { id: 'opt_idi_14_a', option: 'Playing soccer' },
      { id: 'opt_idi_14_b', option: 'Alert and efficient' },
      { id: 'opt_idi_14_c', option: 'Balancing well' },
      { id: 'opt_idi_14_d', option: 'Rolling away' },
    ],
    correctOptionId: 'opt_idi_14_b',
    answerExplanation: 'Alert to new ideas, methods, and trends; efficient and effective.',
  },
  {
    id: 'idi_15',
    type: 'idi',
    question: "What is the meaning of: 'Pull someone's leg'?",
    options: [
      { id: 'opt_idi_15_a', option: 'To trip someone' },
      { id: 'opt_idi_15_b', option: 'To help someone up' },
      { id: 'opt_idi_15_c', option: 'To joke with or tease someone' },
      { id: 'opt_idi_15_d', option: 'To be annoying' },
    ],
    correctOptionId: 'opt_idi_15_c',
    answerExplanation: 'To deceive someone playfully; tease.',
  },
  {
    id: 'idi_16',
    type: 'idi',
    question: "What is the meaning of: 'Sit on the fence'?",
    options: [
      { id: 'opt_idi_16_a', option: 'To rest outside' },
      { id: 'opt_idi_16_b', option: 'To be undecided' },
      { id: 'opt_idi_16_c', option: 'To own property' },
      { id: 'opt_idi_16_d', option: 'To watch neighbors' },
    ],
    correctOptionId: 'opt_idi_16_b',
    answerExplanation: 'Avoid making a decision or choice.',
  },
  {
    id: 'idi_17',
    type: 'idi',
    question: "What is the meaning of: 'Through thick and thin'?",
    options: [
      { id: 'opt_idi_17_a', option: 'Dieting' },
      { id: 'opt_idi_17_b', option: 'Under all circumstances, no matter how difficult' },
      { id: 'opt_idi_17_c', option: 'Traveling through a forest' },
      { id: 'opt_idi_17_d', option: 'Reading a book' },
    ],
    correctOptionId: 'opt_idi_17_b',
    answerExplanation:
      'To support someone or stay together under all circumstances, both good and bad.',
  },
  {
    id: 'idi_18',
    type: 'idi',
    question: "What is the meaning of: 'Let the cat out of the bag'?",
    options: [
      { id: 'opt_idi_18_a', option: 'To release a pet' },
      { id: 'opt_idi_18_b', option: 'To reveal a secret accidentally' },
      { id: 'opt_idi_18_c', option: 'To go shopping' },
      { id: 'opt_idi_18_d', option: 'To solve a problem' },
    ],
    correctOptionId: 'opt_idi_18_b',
    answerExplanation: 'To allow a secret to be known, usually without intending to.',
  },
  {
    id: 'idi_19',
    type: 'idi',
    question: "What is the meaning of: 'Call it a day'?",
    options: [
      { id: 'opt_idi_19_a', option: 'To name something' },
      { id: 'opt_idi_19_b', option: 'To stop working on something' },
      { id: 'opt_idi_19_c', option: 'To start a new job' },
      { id: 'opt_idi_19_d', option: 'To wake up' },
    ],
    correctOptionId: 'opt_idi_19_b',
    answerExplanation: 'Decide to stop working for the day.',
  },
  {
    id: 'idi_20',
    type: 'idi',
    question: "What is the meaning of: 'The best of both worlds'?",
    options: [
      { id: 'opt_idi_20_a', option: 'Traveling to space' },
      {
        id: 'opt_idi_20_b',
        option: 'A situation where you can enjoy the advantages of two different things',
      },
      { id: 'opt_idi_20_c', option: 'Being rich and famous' },
      { id: 'opt_idi_20_d', option: 'Living in two countries' },
    ],
    correctOptionId: 'opt_idi_20_b',
    answerExplanation:
      'A situation in which you can enjoy the advantages of two very different things at the same time.',
  },
  {
    id: 'gra_01',
    type: 'gra',
    question: "Select the correct verb: 'Everyone ___ arrived.'",
    options: [
      { id: 'opt_gra_01_a', option: 'have' },
      { id: 'opt_gra_01_b', option: 'has' },
      { id: 'opt_gra_01_c', option: 'are' },
      { id: 'opt_gra_01_d', option: 'were' },
    ],
    correctOptionId: 'opt_gra_01_b',
    answerExplanation:
      "'Everyone' is a singular indefinite pronoun and requires the singular verb 'has'.",
  },
  {
    id: 'gra_02',
    type: 'gra',
    question: "Identify the error: 'He is good in playing chess.'",
    options: [
      { id: 'opt_gra_02_a', option: 'is' },
      { id: 'opt_gra_02_b', option: 'in' },
      { id: 'opt_gra_02_c', option: 'playing' },
      { id: 'opt_gra_02_d', option: 'chess' },
    ],
    correctOptionId: 'opt_gra_02_b',
    answerExplanation:
      "The correct preposition is 'at'. The sentence should be 'He is good at playing chess.'",
  },
  {
    id: 'gra_03',
    type: 'gra',
    question: "Choose the correct form: 'If I ___ you, I would accept the offer.'",
    options: [
      { id: 'opt_gra_03_a', option: 'was' },
      { id: 'opt_gra_03_b', option: 'am' },
      { id: 'opt_gra_03_c', option: 'were' },
      { id: 'opt_gra_03_d', option: 'be' },
    ],
    correctOptionId: 'opt_gra_03_c',
    answerExplanation:
      "In the subjunctive mood (hypothetical situations), 'were' is used for all subjects.",
  },
  {
    id: 'gra_04',
    type: 'gra',
    question: "Select the correct word: 'The dog wagged ___ tail.'",
    options: [
      { id: 'opt_gra_04_a', option: "it's" },
      { id: 'opt_gra_04_b', option: 'its' },
      { id: 'opt_gra_04_c', option: "its'" },
      { id: 'opt_gra_04_d', option: 'it' },
    ],
    correctOptionId: 'opt_gra_04_b',
    answerExplanation: "'Its' is the possessive form. 'It's' is the contraction for 'it is'.",
  },
  {
    id: 'gra_05',
    type: 'gra',
    question: 'Which sentence is correct?',
    options: [
      { id: 'opt_gra_05_a', option: 'She is more smarter than him.' },
      { id: 'opt_gra_05_b', option: 'She is smarter than him.' },
      { id: 'opt_gra_05_c', option: 'She is most smarter than him.' },
      { id: 'opt_gra_05_d', option: 'She is smart than him.' },
    ],
    correctOptionId: 'opt_gra_05_b',
    answerExplanation: "Do not use 'more' with a comparative adjective ending in -er.",
  },
  {
    id: 'gra_06',
    type: 'gra',
    question: "Select the correct option: 'Neither of the answers ___ correct.'",
    options: [
      { id: 'opt_gra_06_a', option: 'are' },
      { id: 'opt_gra_06_b', option: 'were' },
      { id: 'opt_gra_06_c', option: 'is' },
      { id: 'opt_gra_06_d', option: 'have' },
    ],
    correctOptionId: 'opt_gra_06_c',
    answerExplanation: "'Neither' acts as a singular subject, so it takes the singular verb 'is'.",
  },
  {
    id: 'gra_07',
    type: 'gra',
    question: "Fill in the blank: 'I look forward to ___ you.'",
    options: [
      { id: 'opt_gra_07_a', option: 'see' },
      { id: 'opt_gra_07_b', option: 'seeing' },
      { id: 'opt_gra_07_c', option: 'saw' },
      { id: 'opt_gra_07_d', option: 'seen' },
    ],
    correctOptionId: 'opt_gra_07_b',
    answerExplanation: "The phrase 'look forward to' is followed by a gerund (verb + -ing).",
  },
  {
    id: 'gra_08',
    type: 'gra',
    question: "Choose the correct word: 'They went to ___ house.'",
    options: [
      { id: 'opt_gra_08_a', option: 'there' },
      { id: 'opt_gra_08_b', option: "they're" },
      { id: 'opt_gra_08_c', option: 'their' },
      { id: 'opt_gra_08_d', option: 'theirs' },
    ],
    correctOptionId: 'opt_gra_08_c',
    answerExplanation: "'Their' indicates possession.",
  },
  {
    id: 'gra_09',
    type: 'gra',
    question: "Select the correct option: 'One of the boys ___ missing.'",
    options: [
      { id: 'opt_gra_09_a', option: 'are' },
      { id: 'opt_gra_09_b', option: 'were' },
      { id: 'opt_gra_09_c', option: 'is' },
      { id: 'opt_gra_09_d', option: 'have' },
    ],
    correctOptionId: 'opt_gra_09_c',
    answerExplanation: "The subject is 'One', which is singular.",
  },
  {
    id: 'gra_10',
    type: 'gra',
    question: "Fill in the blank: 'She has been sleeping ___ 2 PM.'",
    options: [
      { id: 'opt_gra_10_a', option: 'for' },
      { id: 'opt_gra_10_b', option: 'since' },
      { id: 'opt_gra_10_c', option: 'from' },
      { id: 'opt_gra_10_d', option: 'until' },
    ],
    correctOptionId: 'opt_gra_10_b',
    answerExplanation: "'Since' is used to denote a specific starting point in time.",
  },
  {
    id: 'gra_11',
    type: 'gra',
    question: "Select the correct pronoun: '___ did you invite to the party?'",
    options: [
      { id: 'opt_gra_11_a', option: 'Who' },
      { id: 'opt_gra_11_b', option: 'Whom' },
      { id: 'opt_gra_11_c', option: 'Whose' },
      { id: 'opt_gra_11_d', option: 'Which' },
    ],
    correctOptionId: 'opt_gra_11_b',
    answerExplanation: "'Whom' is the object of the verb 'invite'.",
  },
  {
    id: 'gra_12',
    type: 'gra',
    question: "Identify the error: 'Please return back the book.'",
    options: [
      { id: 'opt_gra_12_a', option: 'Please' },
      { id: 'opt_gra_12_b', option: 'return' },
      { id: 'opt_gra_12_c', option: 'back' },
      { id: 'opt_gra_12_d', option: 'book' },
    ],
    correctOptionId: 'opt_gra_12_c',
    answerExplanation: "'Return' means to give back, so adding 'back' is redundant (tautology).",
  },
  {
    id: 'gra_13',
    type: 'gra',
    question: "Select the correct quantifier: 'I have ___ money left.'",
    options: [
      { id: 'opt_gra_13_a', option: 'few' },
      { id: 'opt_gra_13_b', option: 'many' },
      { id: 'opt_gra_13_c', option: 'a little' },
      { id: 'opt_gra_13_d', option: 'a few' },
    ],
    correctOptionId: 'opt_gra_13_c',
    answerExplanation:
      "'Money' is uncountable, so 'a little' is correct. 'Few' is for countable nouns.",
  },
  {
    id: 'gra_14',
    type: 'gra',
    question: "Choose the correct article: 'He is ___ honest man.'",
    options: [
      { id: 'opt_gra_14_a', option: 'a' },
      { id: 'opt_gra_14_b', option: 'an' },
      { id: 'opt_gra_14_c', option: 'the' },
      { id: 'opt_gra_14_d', option: 'no article' },
    ],
    correctOptionId: 'opt_gra_14_b',
    answerExplanation: "'Honest' starts with a vowel sound (silent 'h'), so 'an' is used.",
  },
  {
    id: 'gra_15',
    type: 'gra',
    question: "Select the correct form: 'The police ___ coming.'",
    options: [
      { id: 'opt_gra_15_a', option: 'is' },
      { id: 'opt_gra_15_b', option: 'are' },
      { id: 'opt_gra_15_c', option: 'was' },
      { id: 'opt_gra_15_d', option: 'has' },
    ],
    correctOptionId: 'opt_gra_15_b',
    answerExplanation: "'Police' is a plural noun in English.",
  },
  {
    id: 'gra_16',
    type: 'gra',
    question: "Choose the correct verb: 'Bread and butter ___ my favorite breakfast.'",
    options: [
      { id: 'opt_gra_16_a', option: 'are' },
      { id: 'opt_gra_16_b', option: 'is' },
      { id: 'opt_gra_16_c', option: 'were' },
      { id: 'opt_gra_16_d', option: 'have' },
    ],
    correctOptionId: 'opt_gra_16_b',
    answerExplanation:
      "'Bread and butter' is considered a single idea/unit here, taking a singular verb.",
  },
  {
    id: 'gra_17',
    type: 'gra',
    question: "Select the correct option: 'I prefer coffee ___ tea.'",
    options: [
      { id: 'opt_gra_17_a', option: 'than' },
      { id: 'opt_gra_17_b', option: 'to' },
      { id: 'opt_gra_17_c', option: 'over' },
      { id: 'opt_gra_17_d', option: 'from' },
    ],
    correctOptionId: 'opt_gra_17_b',
    answerExplanation: "The verb 'prefer' takes the preposition 'to'.",
  },
  {
    id: 'gra_18',
    type: 'gra',
    question: "Choose the correct adverb placement: 'I ___ go to the gym.'",
    options: [
      { id: 'opt_gra_18_a', option: 'often' },
      { id: 'opt_gra_18_b', option: 'yesterday' },
      { id: 'opt_gra_18_c', option: 'tomorrow' },
      { id: 'opt_gra_18_d', option: 'now' },
    ],
    correctOptionId: 'opt_gra_18_a',
    answerExplanation: "Adverbs of frequency like 'often' usually go before the main verb.",
  },
  {
    id: 'gra_19',
    type: 'gra',
    question: "Fill in the blank: 'Unless you work hard, you ___ succeed.'",
    options: [
      { id: 'opt_gra_19_a', option: 'will' },
      { id: 'opt_gra_19_b', option: 'will not' },
      { id: 'opt_gra_19_c', option: 'cannot' },
      { id: 'opt_gra_19_d', option: 'should' },
    ],
    correctOptionId: 'opt_gra_19_b',
    answerExplanation:
      "'Unless' means 'if... not'. The logic requires 'will not' (you won't succeed if you don't work hard).",
  },
  {
    id: 'gra_20',
    type: 'gra',
    question: "Select the correct form: 'She made me ___ the car.'",
    options: [
      { id: 'opt_gra_20_a', option: 'to wash' },
      { id: 'opt_gra_20_b', option: 'wash' },
      { id: 'opt_gra_20_c', option: 'washed' },
      { id: 'opt_gra_20_d', option: 'washing' },
    ],
    correctOptionId: 'opt_gra_20_b',
    answerExplanation:
      "After causative verbs like 'make' (in active voice), use the base form of the verb without 'to'.",
  },
  {
    id: 'phv_01',
    type: 'phv',
    question: "Select the correct meaning for: 'Call off'",
    options: [
      { id: 'opt_phv_01_a', option: 'To telephone' },
      { id: 'opt_phv_01_b', option: 'To cancel' },
      { id: 'opt_phv_01_c', option: 'To shout' },
      { id: 'opt_phv_01_d', option: 'To visit' },
    ],
    correctOptionId: 'opt_phv_01_b',
    answerExplanation: 'To call off means to cancel an event or agreement.',
  },
  {
    id: 'phv_02',
    type: 'phv',
    question: "Select the correct meaning for: 'Run into'",
    options: [
      { id: 'opt_phv_02_a', option: 'To crash a car' },
      { id: 'opt_phv_02_b', option: 'To meet someone unexpectedly' },
      { id: 'opt_phv_02_c', option: 'To jog inside' },
      { id: 'opt_phv_02_d', option: 'To escape' },
    ],
    correctOptionId: 'opt_phv_02_b',
    answerExplanation: 'To run into someone means to meet them by chance.',
  },
  {
    id: 'phv_03',
    type: 'phv',
    question: "Select the correct meaning for: 'Give up'",
    options: [
      { id: 'opt_phv_03_a', option: 'To donate' },
      { id: 'opt_phv_03_b', option: 'To lift something' },
      { id: 'opt_phv_03_c', option: 'To stop trying' },
      { id: 'opt_phv_03_d', option: 'To start' },
    ],
    correctOptionId: 'opt_phv_03_c',
    answerExplanation: 'To give up means to cease making an effort; resign; quit.',
  },
  {
    id: 'phv_04',
    type: 'phv',
    question: "Select the correct meaning for: 'Put up with'",
    options: [
      { id: 'opt_phv_04_a', option: 'To build' },
      { id: 'opt_phv_04_b', option: 'To tolerate' },
      { id: 'opt_phv_04_c', option: 'To display' },
      { id: 'opt_phv_04_d', option: 'To store' },
    ],
    correctOptionId: 'opt_phv_04_b',
    answerExplanation: 'To put up with means to tolerate or endure someone or something.',
  },
  {
    id: 'phv_05',
    type: 'phv',
    question: "Select the correct meaning for: 'Look after'",
    options: [
      { id: 'opt_phv_05_a', option: 'To stare at' },
      { id: 'opt_phv_05_b', option: 'To take care of' },
      { id: 'opt_phv_05_c', option: 'To follow' },
      { id: 'opt_phv_05_d', option: 'To search' },
    ],
    correctOptionId: 'opt_phv_05_b',
    answerExplanation: 'To look after means to take care of someone or something.',
  },
  {
    id: 'phv_06',
    type: 'phv',
    question: "Select the correct meaning for: 'Bring up'",
    options: [
      { id: 'opt_phv_06_a', option: 'To vomit' },
      { id: 'opt_phv_06_b', option: 'To mention a topic' },
      { id: 'opt_phv_06_c', option: 'To lift' },
      { id: 'opt_phv_06_d', option: 'To arrive' },
    ],
    correctOptionId: 'opt_phv_06_b',
    answerExplanation: 'To bring up means to raise a matter for discussion.',
  },
  {
    id: 'phv_07',
    type: 'phv',
    question: "Select the correct meaning for: 'Turn down'",
    options: [
      { id: 'opt_phv_07_a', option: 'To lower volume' },
      { id: 'opt_phv_07_b', option: 'To reject' },
      { id: 'opt_phv_07_c', option: 'To fold' },
      { id: 'opt_phv_07_d', option: 'To rotate' },
    ],
    correctOptionId: 'opt_phv_07_b',
    answerExplanation:
      'To turn down often means to reject a proposal or offer (can also mean lower volume, but reject is a common test meaning).',
  },
  {
    id: 'phv_08',
    type: 'phv',
    question: "Select the correct meaning for: 'Carry on'",
    options: [
      { id: 'opt_phv_08_a', option: 'To continue' },
      { id: 'opt_phv_08_b', option: 'To hold luggage' },
      { id: 'opt_phv_08_c', option: 'To cry' },
      { id: 'opt_phv_08_d', option: 'To leave' },
    ],
    correctOptionId: 'opt_phv_08_a',
    answerExplanation: 'To carry on means to continue an activity or task.',
  },
  {
    id: 'phv_09',
    type: 'phv',
    question: "Select the correct meaning for: 'Get along'",
    options: [
      { id: 'opt_phv_09_a', option: 'To leave' },
      { id: 'opt_phv_09_b', option: 'To have a friendly relationship' },
      { id: 'opt_phv_09_c', option: 'To walk' },
      { id: 'opt_phv_09_d', option: 'To grow old' },
    ],
    correctOptionId: 'opt_phv_09_b',
    answerExplanation: 'To get along means to have a harmonious or friendly relationship.',
  },
  {
    id: 'phv_10',
    type: 'phv',
    question: "Select the correct meaning for: 'Set up'",
    options: [
      { id: 'opt_phv_10_a', option: 'To sit down' },
      { id: 'opt_phv_10_b', option: 'To arrange or establish' },
      { id: 'opt_phv_10_c', option: 'To upset' },
      { id: 'opt_phv_10_d', option: 'To trick' },
    ],
    correctOptionId: 'opt_phv_10_b',
    answerExplanation: 'To set up means to establish a business, institution, or arrangement.',
  },
  {
    id: 'phv_11',
    type: 'phv',
    question: "Select the correct meaning for: 'Take off'",
    options: [
      { id: 'opt_phv_11_a', option: 'To imitate' },
      { id: 'opt_phv_11_b', option: 'To remove clothes or for a plane to leave the ground' },
      { id: 'opt_phv_11_c', option: 'To steal' },
      { id: 'opt_phv_11_d', option: 'To decrease' },
    ],
    correctOptionId: 'opt_phv_11_b',
    answerExplanation: 'Take off means to become airborne or to remove clothing.',
  },
  {
    id: 'phv_12',
    type: 'phv',
    question: "Select the correct meaning for: 'Break down'",
    options: [
      { id: 'opt_phv_12_a', option: 'To dance' },
      { id: 'opt_phv_12_b', option: 'To stop functioning (machine) or lose control of emotions' },
      { id: 'opt_phv_12_c', option: 'To explain' },
      { id: 'opt_phv_12_d', option: 'To enter forcefully' },
    ],
    correctOptionId: 'opt_phv_12_b',
    answerExplanation: 'Break down means a mechanical failure or an emotional collapse.',
  },
  {
    id: 'phv_13',
    type: 'phv',
    question: "Select the correct meaning for: 'Figure out'",
    options: [
      { id: 'opt_phv_13_a', option: 'To calculate or understand' },
      { id: 'opt_phv_13_b', option: 'To draw' },
      { id: 'opt_phv_13_c', option: 'To see' },
      { id: 'opt_phv_13_d', option: 'To go out' },
    ],
    correctOptionId: 'opt_phv_13_a',
    answerExplanation: 'To figure out means to solve a problem or understand something.',
  },
  {
    id: 'phv_14',
    type: 'phv',
    question: "Select the correct meaning for: 'Hand in'",
    options: [
      { id: 'opt_phv_14_a', option: 'To clap' },
      { id: 'opt_phv_14_b', option: 'To submit' },
      { id: 'opt_phv_14_c', option: 'To hold' },
      { id: 'opt_phv_14_d', option: 'To help' },
    ],
    correctOptionId: 'opt_phv_14_b',
    answerExplanation:
      'To hand in means to give something to a person in authority (e.g., homework).',
  },
  {
    id: 'phv_15',
    type: 'phv',
    question: "Select the correct meaning for: 'Keep on'",
    options: [
      { id: 'opt_phv_15_a', option: 'To stop' },
      { id: 'opt_phv_15_b', option: 'To continue' },
      { id: 'opt_phv_15_c', option: 'To hold' },
      { id: 'opt_phv_15_d', option: 'To wear' },
    ],
    correctOptionId: 'opt_phv_15_b',
    answerExplanation: 'To keep on means to continue doing something.',
  },
  {
    id: 'phv_16',
    type: 'phv',
    question: "Select the correct meaning for: 'Pass out'",
    options: [
      { id: 'opt_phv_16_a', option: 'To distribute or to faint' },
      { id: 'opt_phv_16_b', option: 'To leave' },
      { id: 'opt_phv_16_c', option: 'To die' },
      { id: 'opt_phv_16_d', option: 'To graduate' },
    ],
    correctOptionId: 'opt_phv_16_a',
    answerExplanation: 'Pass out can mean to lose consciousness or to give things to people.',
  },
  {
    id: 'phv_17',
    type: 'phv',
    question: "Select the correct meaning for: 'Show up'",
    options: [
      { id: 'opt_phv_17_a', option: 'To display' },
      { id: 'opt_phv_17_b', option: 'To arrive or appear' },
      { id: 'opt_phv_17_c', option: 'To boast' },
      { id: 'opt_phv_17_d', option: 'To watch' },
    ],
    correctOptionId: 'opt_phv_17_b',
    answerExplanation: 'To show up means to arrive for a gathering or event.',
  },
  {
    id: 'phv_18',
    type: 'phv',
    question: "Select the correct meaning for: 'Work out'",
    options: [
      { id: 'opt_phv_18_a', option: 'To exercise or resolve a problem' },
      { id: 'opt_phv_18_b', option: 'To go to work' },
      { id: 'opt_phv_18_c', option: 'To walk out' },
      { id: 'opt_phv_18_d', option: 'To fail' },
    ],
    correctOptionId: 'opt_phv_18_a',
    answerExplanation: 'Work out means to engage in physical exercise or to find a solution.',
  },
  {
    id: 'phv_19',
    type: 'phv',
    question: "Select the correct meaning for: 'Back up'",
    options: [
      { id: 'opt_phv_19_a', option: 'To reverse or support' },
      { id: 'opt_phv_19_b', option: 'To stand up' },
      { id: 'opt_phv_19_c', option: 'To return' },
      { id: 'opt_phv_19_d', option: 'To turn around' },
    ],
    correctOptionId: 'opt_phv_19_a',
    answerExplanation: 'To back up means to move backwards or to provide support/help.',
  },
  {
    id: 'phv_20',
    type: 'phv',
    question: "Select the correct meaning for: 'Look forward to'",
    options: [
      { id: 'opt_phv_20_a', option: 'To see ahead' },
      { id: 'opt_phv_20_b', option: 'To await with excitement' },
      { id: 'opt_phv_20_c', option: 'To watch' },
      { id: 'opt_phv_20_d', option: 'To plan' },
    ],
    correctOptionId: 'opt_phv_20_b',
    answerExplanation: 'To look forward to means to await something eagerly.',
  },
];
